#!/bin/bash
exit 0

echo "xxxxxDRP preinst called with arguments: $@"
case "$1" in
	"configure")
	;;

	"install"|"upgrade")
	;;

	"abort-upgrade")
	;;

	*)
		echo "ERROR: preinst called with unknown argument \"$1\"" >&2
		exit 1
	;;
esac
